### ISSUE TITLE
Preprocessed Beibei Dataset

### ISSUE THREAD

**Issue by Shawn617** [tsinghua-fib-lab/DGCN#1]
Hi. Great work. I am wondering if you can provide the preprocessed Beibei Dataset for future research. Many thanks in advance.

**Comment by DavyMorgan** [comment]
> Hi. Great work. I am wondering if you can provide the preprocessed Beibei Dataset for future research. Many thanks in advance.

Thanks for your attention on our work. I'm afraid I can not release the Beibei dataset in the short term since it is a private industrial dataset and there is a series of processes to go to make it public. Feel free to use the Taobao dataset!

**Comment by Shawn617** [comment]
OK. I see. Thanks.
