### ISSUE TITLE
Taobao数据集使用

### ISSUE THREAD

**Issue by ManagerYu10** [tsinghua-fib-lab/DGCN#10]
hello~首先感谢开源优秀的工作！
想确认下**data/taobao.zip**是否就是开箱即用的数据结果呢？我理解taobao.zip解压出来的**XX.npz**文件应该等于原始**UserBehavior.csv**被taobao.py处理后的结果吧

**Comment by DavyMorgan** [comment]
是的，npz文件就是处理后用于实验的数据
