### ISSUE TITLE
Can you provide code of the module "data_process_service" 

### ISSUE THREAD

**Issue by YahongANN** [tsinghua-fib-lab/DGCN#11]
Hi:
    In Taobao dataset folder, I notice there are missing the code implementation about "data_process_service". Since, I want to use my own datasets, can you provide the implementation of the code module?
   Looking forward to your reply!

**Comment by DavyMorgan** [comment]
Hi, the data process service codes are available here at [https://github.com/DavyMorgan/dps](https://github.com/DavyMorgan/dps)
