### ISSUE TITLE
Running Issues

### ISSUE THREAD

**Issue by Shawn617** [tsinghua-fib-lab/DGCN#2]
Hi. I got this issue when I run the code. 
"Please turn it into an immutable graph with DGLGraphStale.readonly"
AssertionError: NeighborSampler doesn't support mutable graphs. Please turn it into an immutable graph with DGLGraphStale.readonly

Seems it got the error at File "recommender.py", line 161, in inference
    data_flows, node_index, user_index, item_index = self.gm.point_sample_neighbors(user, item).

Do you have ideas? BTW, could you also please provide the version of the DGL and pytorch? Mant thanks

**Comment by DavyMorgan** [comment]
> Hi. I got this issue when I run the code.
> "Please turn it into an immutable graph with DGLGraphStale.readonly"
> AssertionError: NeighborSampler doesn't support mutable graphs. Please turn it into an immutable graph with DGLGraphStale.readonly
> 
> Seems it got the error at File "recommender.py", line 161, in inference
> data_flows, node_index, user_index, item_index = self.gm.point_sample_neighbors(user, item).
> 
> Do you have ideas? BTW, could you also please provide the version of the DGL and pytorch? Mant thanks

Hi, I guess the error is due to the package version issue. Specifically, my environment has PyTorch 1.1.0 and DGL 0.4.1. Good Luck!
