### ISSUE TITLE
求解pytorch和dgl的相关版本号

### ISSUE THREAD

**Issue by LayneChai** [tsinghua-fib-lab/DGCN#8]
你好，能提供一下这个pytorch和dgl的版本号吗，谢谢，在论文和代码中没有看到相关版本

**Comment by DavyMorgan** [comment]
你好，我们实验的版本是torch 1.1和dgl 0.4.1

**Comment by LayneChai** [comment]
好的，谢谢

**Comment by LayneChai** [comment]
你好，我尝试运行了，但是我看GPU的使用率只有2%，你们实验室在运行代码的时候，有遇到这个问题吗，我看到代码中有user.to(self.device)  item.to(self.device),但是GPU的使用率几乎没有使用，谢谢

我的运行环境是2080ti

**Comment by DavyMorgan** [comment]
可以看一看显存的占用，正常运行应该就没有问题的。

**Comment by LayneChai** [comment]
好的，谢谢
